from tkinter import *
from tkinter import ttk
def function(root):
    frame= Frame(root, bg= '#fed8b1')
    frame.place(relwidth= 1, relheight= 1)
    def back_button_function(*args):
        frame.destroy()
    def next_button_function(*args):
        frame= Frame(root, bg= '#fed8b1')
        frame.place(relwidth= 1, relheight= 1)
        def back_button_function(*args):
            frame.destroy()
        def save_button_function(*args):
            true_false.config(state= 'disabled')
            true_false2.config(state= 'disabled')
            true_false3.config(state= 'disabled')
            true_false4.config(state= 'disabled')
            true_false5.config(state= 'disabled')
            true_false6.config(state= 'disabled')
            true_false7.config(state= 'disabled')
            true_false8.config(state= 'disabled')
            true_false9.config(state= 'disabled')
            true_false10.config(state= 'disabled')
            true_false11.config(state= 'disabled')
            true_false12.config(state= 'disabled')
            true_false13.config(state= 'disabled')
            true_false14.config(state= 'disabled')
            true_false15.config(state= 'disabled')
            true_false16.config(state= 'disabled')
            true_false17.config(state= 'disabled')
            true_false18.config(state= 'disabled')
            true_false19.config(state= 'disabled')
            true_false20.config(state= 'disabled')
            edit_button.config(state= 'normal')
            save_button.config(state= 'disabled')
        def edit_button_function(*args):
            true_false.config(state= 'normal')
            true_false2.config(state= 'normal')
            true_false3.config(state= 'normal')
            true_false4.config(state= 'normal')
            true_false5.config(state= 'normal')
            true_false6.config(state= 'normal')
            true_false7.config(state= 'normal')
            true_false8.config(state= 'normal')
            true_false9.config(state= 'normal')
            true_false10.config(state= 'normal')
            true_false11.config(state= 'normal')
            true_false12.config(state= 'normal')
            true_false13.config(state= 'normal')
            true_false14.config(state= 'normal')
            true_false15.config(state= 'normal')
            true_false16.config(state= 'normal')
            true_false17.config(state= 'normal')
            true_false18.config(state= 'normal')
            true_false19.config(state= 'normal')
            true_false20.config(state= 'normal')
            edit_button.config(state= 'disabled')
            save_button.config(state= 'normal')

        made_by = Label(frame, text='Made by Mikiyas kibrom', bg='#fed8b1', fg='#0000ff')
        made_by.place(relx=0.7, rely=0.05)
        title= Label(frame, text= 'True/False 20Q', font= ('tkfixedfont 15', 20, 'bold'), bg= '#fed8b1')
        title.place(relx= 0.3, rely= 0.1)
        number15= Label(frame, text= '15.', font= ('tkfixedfont 15', 15, 'italic'), bg= '#fed8b1')
        number15.place(relx= 0.001, rely= 0.2)
        true_false15= ttk.Combobox(frame, value= true_false_list, state= 'normal')
        true_false15.current(0)
        true_false15.place(relx= 0.065, rely= 0.21)
        number16= Label(frame, text= '16.', font= ('tkfixedfont 15', 15, 'italic'), bg= '#fed8b1')
        number16.place(relx= 0.001, rely= 0.31)
        true_false16= ttk.Combobox(frame, value= true_false_list, state= 'normal')
        true_false16.current(0)
        true_false16.place(relx= 0.065, rely= 0.32)
        number17= Label(frame, text= '17.', font= ('tkfixedfont 15', 15, 'italic'), bg= '#fed8b1')
        number17.place(relx= 0.001, rely= 0.41)
        true_false17= ttk.Combobox(frame, value= true_false_list, state= 'normal')
        true_false17.current(0)
        true_false17.place(relx= 0.065, rely= 0.42)
        number18= Label(frame, text= '18.', font= ('tkfixedfont 15', 15, 'italic'), bg= '#fed8b1')
        number18.place(relx= 0.001, rely= 0.51)
        true_false18= ttk.Combobox(frame, value= true_false_list, state= 'normal')
        true_false18.current(0)
        true_false18.place(relx= 0.065, rely= 0.52)
        number19= Label(frame, text= '19.', font= ('tkifxedfont 15', 15, 'italic'), bg= '#fed8b1')
        number19.place(relx= 0.001, rely= 0.61)
        true_false19= ttk.Combobox(frame, value= true_false_list, state= 'normal')
        true_false19.current(0)
        true_false19.place(relx= 0.065, rely= 0.62)
        number20= Label(frame, text= '20', font= ('tkfixedfont 15', 15, 'italic'), bg= '#fed8b1')
        number20.place(relx= 0.001, rely= 0.71)
        true_false20= ttk.Combobox(frame, value= true_false_list, state= 'normal')
        true_false20.current(0)
        true_false20.place(relx= 0.065, rely= 0.72)

        back_button = ttk.Button(frame, text='Back', command=back_button_function)
        back_button.place(relx=0.001, rely=0.94)
        edit_button = ttk.Button(frame, text='Edit', state='disabled', command= edit_button_function)
        edit_button.place(relx=0.4, rely=0.94)
        save_button = ttk.Button(frame, text='Save', command=save_button_function)
        save_button.place(relx=0.85, rely=0.94)
    title= Label(frame, text= 'True/False 20Q', font= ('tkfixedfont 15', 20, 'bold'), bg= '#fed8b1')
    title.place(relx= 0.3, rely= 0.1)
    made_by= Label(frame, text= 'Made by Mikiyas kibrom', bg= '#fed8b1', fg= '#0000ff')
    made_by.place(relx= 0.7, rely= 0.05)
    true_false_list= [
        'True',
        'False'
    ]

    number1= Label(frame, text= '1.', font= ('tkfixedfont 15', 15, 'italic'), bg= '#fed8b1')
    number1.place(relx= 0.001, rely= 0.20)
    true_false= ttk.Combobox(frame, value= true_false_list, state= 'normal')
    true_false.current(0)
    true_false.place(relx= 0.04, rely= 0.21)
    number2= Label(frame, text= '2.', font= ('tkfixedfont 15', 15, 'italic'), bg= '#fed8b1')
    number2.place(relx= 0.001, rely= 0.30)
    true_false2= ttk.Combobox(frame, value= true_false_list, state= 'normal')
    true_false2.current(0)
    true_false2.place(relx= 0.04, rely= 0.31)
    number3= Label(frame, text= '3.', font= ('tkfixedfont 15', 15, 'italic'), bg= '#fed8b1')
    number3.place(relx= 0.001, rely= 0.41)
    true_false3= ttk.Combobox(frame, value= true_false_list, state= 'normal')
    true_false3.current(0)
    true_false3.place(relx= 0.04, rely= 0.42)
    number4= Label(frame, text= '4.', font= ('tkfixedfont 15', 15, 'italic'), bg= '#fed8b1')
    number4.place(relx= 0.001, rely= 0.51)
    true_false4= ttk.Combobox(frame, value= true_false_list, state= 'normal')
    true_false4.current(0)
    true_false4.place(relx= 0.04, rely= 0.52)
    number5= Label(frame, text= '5.', font= ('tkfixedfont 15', 15, 'italic'), bg= '#fed8b1')
    number5.place(relx= 0.001, rely= 0.61)
    true_false5= ttk.Combobox(frame, value= true_false_list, state= 'normal')
    true_false5.current(0)
    true_false5.place(relx= 0.04, rely= 0.62)
    number6= Label(frame, text= '6.', font= ('tkifxedfont 15', 15, 'italic'), bg= '#fed8b1')
    number6.place(relx= 0.001, rely= 0.71)
    true_false6= ttk.Combobox(frame, value= true_false_list, state= 'normal')
    true_false6.current(0)
    true_false6.place(relx= 0.04, rely= 0.72)
    number7= Label(frame, text= '7.', font= ('tkfixedfont 15', 15, 'italic'), bg= '#fed8b1')
    number7.place(relx= 0.001, rely= 0.81)
    true_false7= ttk.Combobox(frame, value= true_false_list, state= 'normal')
    true_false7.current(0)
    true_false7.place(relx= 0.04, rely= 0.82)
    number8= Label(frame, text= '8.', font= ('tkfixedfont 15', 15, 'italic'), bg= '#fed8b1')
    number8.place(relx= 0.7, rely= 0.21)
    true_false8= ttk.Combobox(frame, value= true_false_list, state= 'normal')
    true_false8.current(0)
    true_false8.place(relx= 0.74, rely= 0.22)
    number9= Label(frame, text= '9.', font= ('tkfixedfont 15', 15, 'italic'), bg= '#fed8b1')
    number9.place(relx= 0.7, rely= 0.31)
    true_false9= ttk.Combobox(frame, value= true_false_list, state= 'normal')
    true_false9.current(0)
    true_false9.place(relx= 0.74, rely= 0.32)
    number10= Label(frame, text= '10.', font= ('tkfixedfont 15', 15, 'italic'), bg= '#fed8b1')
    number10.place(relx= 0.68, rely= 0.41)
    true_false10= ttk.Combobox(frame, value= true_false_list, state= 'normal')
    true_false10.current(0)
    true_false10.place(relx= 0.74, rely= 0.42)
    number11= Label(frame, text= '11.', font= ('tkfixedfont 15', 15, 'italic'), bg= '#fed8b1')
    number11.place(relx= 0.68, rely= 0.51 )
    true_false11= ttk.Combobox(frame, value= true_false_list, state= 'normal')
    true_false11.current(0)
    true_false11.place(relx= 0.74, rely= 0.52)
    number12= Label(frame, text= '12', font= ('tkfixedfont 15', 15, 'italic'), bg= '#fed8b1')
    number12.place(relx= 0.68, rely= 0.61)
    true_false12= ttk.Combobox(frame, value= true_false_list, state= 'normal')
    true_false12.current(0)
    true_false12.place(relx= 0.74, rely= 0.62)
    number13= Label(frame, text= '13.', font= ('tkfixedfont 15', 15, 'italic'), bg= '#fed8b1')
    number13.place(relx= 0.68, rely= 0.71)
    true_false13= ttk.Combobox(frame, value= true_false_list, state= 'normal')
    true_false13.current(0)
    true_false13.place(relx= 0.74, rely= 0.72)
    number14= Label(frame, text= '14.', font= ('tkfixedfont 15', 15, 'italic'), bg= '#fed8b1')
    number14.place(relx= 0.68, rely= 0.81)
    true_false14= ttk.Combobox(frame, value= true_false_list, state= 'normal')
    true_false14.current(0)
    true_false14.place(relx= 0.74, rely= 0.82)

    back_button= ttk.Button(frame, text= 'Back', command= back_button_function)
    back_button.place(relx= 0.001, rely= 0.94)
    next_button= ttk.Button(frame, text= 'Next', command= next_button_function)
    next_button.place(relx= 0.85, rely= 0.94)