from tkinter import *
from tkinter import ttk
def function(root):
    frame= Frame(root, bg= '#fed8b1')
    frame.place(relwidth= 1, relheight= 1)
    def back_button_function(*args):
        frame.destroy()
    def save_button_function(*args):
        true_false.config(state= 'disabled')
        true_false2.config(state= 'disabled')
        true_false3.config(state= 'disabled')
        true_false4.config(state= 'disabled')
        true_false5.config(state= 'disabled')
        true_false6.config(state= 'disabled')
        true_false7.config(state= 'disabled')
        true_false8.config(state= 'disabled')
        true_false9.config(state= 'disabled')
        true_false10.config(state= 'disabled')
        edit_button.config(state= 'normal')
        save_button.config(state= 'disabled')
    def edit_button_function(*args):
        true_false.config(state= 'normal')
        true_false2.config(state= 'normal')
        true_false3.config(state= 'normal')
        true_false4.config(state= 'normal')
        true_false5.config(state= 'normal')
        true_false6.config(state= 'normal')
        true_false7.config(state= 'normal')
        true_false8.config(state= 'normal')
        true_false9.config(state= 'normal')
        true_false10.config(state= 'normal')
        edit_button.config(state= 'disabled')
        save_button.config(state= 'normal')
    title= Label(frame, text= 'True/False 10Q', font= ('tkfixedfont 15', 20, 'bold'), bg= '#fed8b1')
    title.place(relx= 0.3, rely= 0.1)
    number1= Label(frame, text= '1.', bg= '#fed8b1', font= ('tkfixedfont 15', 15, 'italic'))
    number1.place(relx= 0.001, rely= 0.2)
    made_by= Label(frame, text= 'Made by Mikiyas kibrom', bg= '#fed8b1', fg= '#0000ff')
    made_by.place(relx= 0.7, rely= 0.05)
    true_false_list= [
        'True',
        'False'
    ]

    true_false= ttk.Combobox(frame, value= true_false_list, state= 'normal')
    true_false.current(0)
    true_false.place(relx= 0.04, rely= 0.21)
    number2= Label(frame, text= '2.', font= ('tkfixedfont 15', 15, 'italic'), bg= '#fed8b1')
    number2.place(relx= 0.001, rely= 0.30)
    true_false2= ttk.Combobox(frame, value= true_false_list, state= 'normal')
    true_false2.current(0)
    true_false2.place(relx= 0.04, rely= 0.31)
    number3= Label(frame, text= '3.', font= ('tkfixedfont 15', 15, 'italic'), bg= '#fed8b1')
    number3.place(relx= 0.001, rely= 0.41)
    true_false3= ttk.Combobox(frame, value= true_false_list, state= 'normal')
    true_false3.current(0)
    true_false3.place(relx= 0.04, rely= 0.42)
    number4= Label(frame, text= '4.', font= ('tkfixedfont 15', 15, 'italic'), bg= '#fed8b1')
    number4.place(relx= 0.001, rely= 0.51)
    true_false4= ttk.Combobox(frame, value= true_false_list, state= 'normal')
    true_false4.current(0)
    true_false4.place(relx= 0.04, rely= 0.52)
    number5= Label(frame, text= '5.', font= ('tkfixedfont 15', 15, 'italic'), bg= '#fed8b1')
    number5.place(relx= 0.001, rely= 0.61)
    true_false5= ttk.Combobox(frame, value= true_false_list, state= 'normal')
    true_false5.current(0)
    true_false5.place(relx= 0.04, rely= 0.62)
    number6= Label(frame, text= '6.', font= ('tkifxedfont 15', 15, 'italic'), bg= '#fed8b1')
    number6.place(relx= 0.001, rely= 0.71)
    true_false6= ttk.Combobox(frame, value= true_false_list, state= 'normal')
    true_false6.current(0)
    true_false6.place(relx= 0.04, rely= 0.72)
    number7= Label(frame, text= '7.', font= ('tkfixedfont 15', 15, 'italic'), bg= '#fed8b1')
    number7.place(relx= 0.001, rely= 0.81)
    true_false7= ttk.Combobox(frame, value= true_false_list, state= 'normal')
    true_false7.current(0)
    true_false7.place(relx= 0.04, rely= 0.82)
    number8= Label(frame, text= '8.', font= ('tkfixedfont 15', 15, 'italic'), bg= '#fed8b1')
    number8.place(relx= 0.7, rely= 0.21)
    true_false8= ttk.Combobox(frame, value= true_false_list, state= 'normal')
    true_false8.current(0)
    true_false8.place(relx= 0.74, rely= 0.22)
    number9= Label(frame, text= '9.', font= ('tkfixedfont 15', 15, 'italic'), bg= '#fed8b1')
    number9.place(relx= 0.7, rely= 0.31)
    true_false9= ttk.Combobox(frame, value= true_false_list, state= 'normal')
    true_false9.current(0)
    true_false9.place(relx= 0.74, rely= 0.32)
    number10= Label(frame, text= '10.', font= ('tkfixedfont 15', 15, 'italic'), bg= '#fed8b1')
    number10.place(relx= 0.68, rely= 0.41)
    true_false10= ttk.Combobox(frame, value= true_false_list, state= 'normal')
    true_false10.current(0)
    true_false10.place(relx= 0.74, rely= 0.42)

    back_button= ttk.Button(frame, text= 'Back', command= back_button_function)
    back_button.place(relx= 0.001, rely= 0.94)
    edit_button= ttk.Button(frame, text= 'Edit', state= 'disabled', command= edit_button_function)
    edit_button.place(relx= 0.4, rely= 0.94)
    save_button= ttk.Button(frame, text= 'Save', command= save_button_function)
    save_button.place(relx= 0.85, rely= 0.94)